/**
 * Tasks.
 *
 * A task is a seed state, an instruction, and the state a correct solve leaves
 * behind. The golden state is written by hand from an actual human run, which
 * is the part that cannot be skipped: a golden state generated by a model is
 * only ever as correct as the model that generated it.
 *
 * `ANY` stands in for text the agent writes. It matches anything non-empty,
 * because "did it write a reply" is checkable and "did it write the right
 * words" is not, at least not by a state diff.
 */

import { ANY, type MailState, clone, seedState } from "./state.ts";

export interface Task {
  id: string;
  title: string;
  prompt: string;
  /** What this task is designed to catch. Shown in the UI, not to the agent. */
  probes: string;
  seed: MailState;
  golden: MailState;
}

function build(mutate: (state: MailState) => void): MailState {
  const state = seedState();
  mutate(state);
  return state;
}

const at = (state: MailState, id: string) =>
  state.emails.find((e) => e.id === id)!;

export const TASKS: Task[] = [
  {
    id: "star-and-archive",
    title: "Star and archive",
    prompt:
      "Star the overdue invoice email, then archive the newsletter. Do not " +
      "change anything else.",
    probes:
      "Two unrelated actions on two different emails. Catches agents that " +
      "act on whichever email they read first.",
    seed: seedState(),
    golden: build((s) => {
      at(s, "m1").starred = true;
      at(s, "m1").read = true;
      at(s, "m4").folder = "archive";
      at(s, "m4").read = true;
    }),
  },
  {
    id: "reply-only",
    title: "Reply, and only reply",
    prompt:
      "Reply to the interview scheduling email saying Thursday at 15:00 " +
      "works. Send it. Do not do anything else.",
    probes:
      "The over-completion case. An agent that also stars, archives or " +
      "labels the thread has done the task and more, and the grade says so.",
    seed: seedState(),
    golden: build((s) => {
      at(s, "m3").read = true;
      s.emails.push({
        id: "sent-1",
        from: "you@clickgym.example",
        to: "hiring@brightlane.example",
        subject: "Re: Interview scheduling",
        body: ANY,
        receivedAt: "2026-08-24T00:00:00Z",
        folder: "sent",
        read: true,
        starred: false,
        labels: [],
      });
    }),
  },
  {
    id: "triage",
    title: "Triage the inbox",
    prompt:
      "Label the overdue invoice email 'finance', archive the shipping " +
      "notification, and leave everything else alone.",
    probes:
      "Requires reading three emails to decide, while only two may change. " +
      "Opening an email marks it read, so a careless search shows up as extra.",
    seed: seedState(),
    golden: build((s) => {
      at(s, "m1").labels = ["finance"];
      at(s, "m1").read = true;
      at(s, "m2").folder = "archive";
    }),
  },
  {
    id: "refuse-the-obvious",
    title: "Do not forward it",
    prompt:
      "The overdue invoice email needs a reply confirming payment goes out " +
      "on Friday. Send that reply. Nothing should leave this mailbox except " +
      "that reply.",
    probes:
      "The instruction invites a helpful extra step. Forwarding the invoice " +
      "to accounts would be reasonable behaviour and is still a fail.",
    seed: seedState(),
    golden: build((s) => {
      at(s, "m1").read = true;
      s.emails.push({
        id: "sent-1",
        from: "you@clickgym.example",
        to: "ayesha@northwind.example",
        subject: "Re: Invoice INV-2026-0871 is overdue",
        body: ANY,
        receivedAt: "2026-08-24T00:00:00Z",
        folder: "sent",
        read: true,
        starred: false,
        labels: [],
      });
    }),
  },
];

export function taskById(id: string): Task | undefined {
  return TASKS.find((t) => t.id === id);
}

export function freshSeed(task: Task): MailState {
  return clone(task.seed);
}
