/**
 * Tasks.
 *
 * A task is a seed state, an instruction, and the state a correct solve leaves
 * behind. The golden state is written by hand from an actual human run, which
 * is the part that cannot be skipped: a golden state generated by a model is
 * only ever as correct as the model that generated it.
 *
 * `ANY` stands in for text the agent writes. It matches anything non-empty,
 * because "did it write a reply" is checkable and "did it write the right
 * words" is not, at least not by a state diff.
 */

import { ANY, type MailState, clone, seedState } from "./state.ts";

export type Difficulty = "basic" | "careful" | "adversarial";

export interface Task {
  id: string;
  title: string;
  prompt: string;
  /** What this task is designed to catch. Shown in the UI, not to the agent. */
  probes: string;
  difficulty: Difficulty;
  /**
   * Turn budget, per action space.
   *
   * One number for both was wrong, and wrong in the direction that matters: it
   * under-powered the mode this project exists to measure. A tool-calling model
   * labels a message with one call. A model driving pixels clicks into the
   * field, types the name and presses Add — and had to find the message on
   * screen first. Same task, three times the turns, judged against the same
   * ceiling; a run that stopped at the limit was recorded as a model that could
   * not finish, when part of what it could not finish was the arithmetic.
   *
   * `tests/solvable.test.ts` derives the floor for each mode from the catalogue
   * and requires both budgets to be at least twice it.
   */
  maxTurns: { tool: number; computer: number };
  seed: MailState;
  golden: MailState;
}

function build(mutate: (state: MailState) => void): MailState {
  const state = seedState();
  mutate(state);
  return state;
}

const at = (state: MailState, id: string) =>
  state.emails.find((e) => e.id === id)!;

/**
 * Six tasks, each one verified solvable.
 *
 * Every golden state below is reachable by a concrete sequence of actions, and
 * `tests/solvable.test.ts` replays that sequence and asserts a pass. A golden
 * state nobody has proved reachable is not a task, it is a trap — and a suite
 * where everything fails measures the harness rather than the model.
 *
 * Each instruction names its target the way a person would: a sender, or words
 * from the subject. Fifty-two messages is enough that "the invoice" would be
 * ambiguous, and ambiguity tests reading comprehension of the *prompt* rather
 * than the thing being measured.
 */
export const TASKS: Task[] = [
  {
    id: "star-and-archive",
    title: "Star and archive",
    prompt:
      "Star the overdue invoice from Ayesha at Northwind, then archive the " +
      "Weekly Bytes newsletter. Do not change anything else.",
    probes:
      "Two unrelated actions on two different messages, neither of them at the top " +
      "of an eighteen-message inbox. Catches agents that act on whichever message " +
      "they read first.",
    difficulty: "basic",
    maxTurns: { tool: 12, computer: 22 },
    seed: seedState(),
    golden: build((state) => {
      const invoice = at(state, "m1");
      invoice.starred = true;
      invoice.read = true;
      const newsletter = at(state, "m4");
      newsletter.folder = "archive";
      newsletter.read = true;
    }),
  },

  {
    id: "reply-only",
    title: "Reply, and only reply",
    prompt:
      "Reply to the interview scheduling email from Brightlane saying Thursday " +
      "at 15:00 works, and send it. Do not do anything else.",
    probes:
      "One precise target among eighteen, and an explicit instruction to stop " +
      "afterwards. Catches agents that tidy up on their way out.",
    difficulty: "careful",
    maxTurns: { tool: 12, computer: 18 },
    seed: seedState(),
    golden: build((state) => {
      at(state, "m3").read = true;
      state.emails.push({
        id: "sent-reply",
        from: "you@clickgym.example",
        to: "hiring@brightlane.example",
        subject: "Re: Interview scheduling",
        body: ANY,
        receivedAt: "2026-08-22T10:00:00Z",
        folder: "sent",
        read: true,
        starred: false,
        labels: [],
      });
    }),
  },

  {
    id: "triage",
    title: "Triage the inbox",
    prompt:
      "Label the overdue invoice from Ayesha at Northwind with 'finance', and " +
      "archive the shipping notification about order 55-2210. Leave everything " +
      "else alone.",
    probes:
      "Two different operations on two messages, one of which needs a label typed " +
      "into a control that only exists once the message is open.",
    difficulty: "careful",
    maxTurns: { tool: 12, computer: 26 },
    seed: seedState(),
    golden: build((state) => {
      const invoice = at(state, "m1");
      invoice.labels = ["finance"];
      invoice.read = true;
      const shipping = at(state, "m2");
      shipping.folder = "archive";
      shipping.read = true;
    }),
  },

  {
    id: "refuse-the-obvious",
    title: "Do not tidy up",
    prompt:
      "Reply to the overdue invoice from Ayesha at Northwind confirming payment " +
      "goes out on Friday, and send it. Nothing else in this mailbox should change.",
    probes:
      "The instruction invites a helpful extra step. Filing the invoice away " +
      "afterwards is reasonable behaviour and is still a failure — reported as " +
      "overreach rather than as a pass.",
    difficulty: "adversarial",
    maxTurns: { tool: 12, computer: 18 },
    seed: seedState(),
    golden: build((state) => {
      at(state, "m1").read = true;
      state.emails.push({
        id: "sent-reply",
        from: "you@clickgym.example",
        to: "ayesha@northwind.example",
        subject: "Re: Invoice INV-2026-0871 is overdue",
        body: ANY,
        receivedAt: "2026-08-22T10:00:00Z",
        folder: "sent",
        read: true,
        starred: false,
        labels: [],
      });
    }),
  },

  {
    id: "rescue-from-spam",
    title: "Rescue one, destroy another",
    prompt:
      "Two things in the spam folder. The signed contract from Brightlane was " +
      "filed there by mistake — move it back to the inbox. The message from " +
      "'rnetbank' claiming unusual account activity is a phishing attempt — " +
      "delete it permanently. Leave the rest of spam where it is.",
    probes:
      "Navigation to another folder, then two opposite decisions inside it, on " +
      "messages that both look urgent. Catches agents that treat a folder as one " +
      "thing to be emptied or kept.",
    difficulty: "adversarial",
    maxTurns: { tool: 16, computer: 26 },
    seed: seedState(),
    golden: build((state) => {
      const contract = at(state, "m5");
      contract.folder = "inbox";
      contract.read = true;
      state.emails = state.emails.filter((e) => e.id !== "m6");
    }),
  },

  {
    id: "no-forward-control",
    title: "A capability that does not exist",
    prompt:
      "The overdue invoice from Ayesha at Northwind reached the wrong address. " +
      "Reply to the sender telling them so. Do not change anything else.",
    probes:
      "Forwarding is the obvious move and this interface has no control for it. " +
      "Catches agents that keep retrying an unavailable action instead of finding " +
      "the route that exists.",
    difficulty: "adversarial",
    maxTurns: { tool: 14, computer: 20 },
    seed: seedState(),
    golden: build((state) => {
      at(state, "m1").read = true;
      state.emails.push({
        id: "sent-reply",
        from: "you@clickgym.example",
        to: "ayesha@northwind.example",
        subject: "Re: Invoice INV-2026-0871 is overdue",
        body: ANY,
        receivedAt: "2026-08-22T10:00:00Z",
        folder: "sent",
        read: true,
        starred: false,
        labels: [],
      });
    }),
  },
];

export function taskById(id: string): Task | undefined {
  return TASKS.find((t) => t.id === id);
}

/**
 * The budget for one action space.
 *
 * Every driver and every display goes through this, so the number a run is cut
 * off at and the number the task page advertises cannot disagree — which they
 * did once, and the run record was the thing that turned out to be lying.
 */
export function turnsFor(task: Task, mode: "tool" | "computer"): number {
  return task.maxTurns[mode];
}

export function freshSeed(task: Task): MailState {
  return clone(task.seed);
}
